### PR TITLE
Added nuspec file

### PR DESCRIPTION
**Pull request by dsmit**
Added nuspec file. If you want I can push it to nuget its main repository too. The information filled in the nuspec file correct so far?

Thanks.

### CODE REVIEW

**Comment by duelinmarkers** [comment]
Merged and tweaked.

**Comment by dsmit** [comment]
Cool! Will you push it into nuget or should I do that?

**Comment by duelinmarkers** [comment]
Please feel free. Thanks.

-- typed with my thumbs
On Nov 10, 2011 10:42 AM, "Dennis Smit" <
reply@reply.github.com>
wrote:

**Comment by dsmit** [comment]
Done

**Pull request merged**
